name: Build App

on:
  push:
    branches:
      - main  # 你可以改成你的主分支名
  pull_request:
  release:
    types: [created]  # 触发条件：创建一个 Release 时

jobs:
  build:
    runs-on: windows-latest  # ✅ 修改为 Windows 运行环境

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 拉取代码

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"  # 你可以改成你的 Python 版本

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装项目依赖
          pip install pyinstaller  # 安装 PyInstaller

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"  # ✅ 你可以根据需要修改 Node.js 版本

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install  # ✅ 先安装依赖

      - name: Build Frontend
        run: |
          cd frontend
          npm run build  # ✅ 构建前端

      - name: Build Executable
        run: pyinstaller --name=风控 --add-data "config;config" --add-data "frontend/build;frontend/build" --console app.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 风控
          path: dist/  # 打包后的文件夹
          retention-days: 5  # 5 天后自动删除
